[package]
name = "arrow_deps"
version = "0.1.0"
authors = ["yutiansut@qq.com"]
edition = "2018"
description = "Apache Arrow / Parquet / DataFusion dependencies for QADATA"



[dependencies]
# We are using development version of arrow/parquet/datafusion and the dependencies are at the same rev

# The version can be found here: https://gitee.com/yutiansut/arrow/commit/c46fd102678fd22b9781642437ad8821f907d9db
#
arrow = { git = "https://gitee.com/yutiansut/arrow.git", rev = "c46fd102678fd22b9781642437ad8821f907d9db" , features = ["simd"] }
datafusion = { git = "https://gitee.com/yutiansut/arrow.git", rev = "c46fd102678fd22b9781642437ad8821f907d9db" }
# Turn off the "arrow" feature; it currently has a bug that causes the crate to rebuild every time
# and we're not currently using it anyway
parquet = { git = "https://gitee.com/yutiansut/arrow.git", rev = "c46fd102678fd22b9781642437ad8821f907d9db", default-features = false, features = ["snap", "brotli", "flate2", "lz4", "zstd"] }
parquet_derive = { git = "https://gitee.com/yutiansut/arrow.git", rev = "c46fd102678fd22b9781642437ad8821f907d9db" }
